version: "3.8"
services:
  nginx:
    depends_on:
      - frontend
    container_name: nginx_c
    build: ./nginx
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./frontend/build:/usr/share/nginx/html
  frontend:
    container_name: frontend_c
    build: ./frontend
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - . :/usr/src/app
  backend:
    container_name: backend_c
    build: ./backend
    restart: always
    ports:
      - '4000:4000'
    volumes:
      - . :/usr/src/app
    stdin_open: true
    tty: true
