version: "3.8"
services:
  frontend:
    container_name: frontend_c
    build: ./frontend
    restart: always
    ports:
      - '3000:3000'
  backend:
    container_name: backend_c
    build: ./backend
    restart: always
    ports:
      - '4000:4000'
    stdin_open: true
    tty: true
  nginx:
    container_name: nginx_c
    image: nginx:1-alpine
    restart: always
    ports:
      - '8089:80'
    volumes:
      - ./frontend/build/:/var/www/html
      - ./frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
