version: "3.8"
services:
  nginx:
    depends_on:
      - frontend
      - backend
    container_name: nginx_c
    build: ./nginx
    restart: always
    ports:
      - '80:80'
  frontend:
    container_name: frontend_c
    build: ./frontend
    restart: always
    ports:
      - '3000:3000'
  backend:
    container_name: backend_c
    build: ./backend
    restart: always
    ports:
      - '4000:4000'
    stdin_open: true
    tty: true
