version: "3.8"
services:

  frontend:
    container_name: frontend_c
    build: ./frontend
    restart: always
    ports:
      - '80:80'
      - '443:443'

  backend:
    container_name: backend_c
    build: ./backend
    restart: always
    env_file: .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    stdin_open: true
    tty: true
    depends_on:
      - database

  database:
    container_name: ${DATABASE_HOST}
    build: ./database
    restart: always
    env_file: .env
    ports: 
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - database_v:/data/db
      - configdatabase_v:/data/configdb

volumes:
  database_v:
  configdatabase_v: