version: "3.8"
services:
  frontend:
    container_name: frontend_c
    build: ./frontend
    restart: always
  backend:
    container_name: backend_c
    build: ./backend
    restart: always
    ports:
      - '4000:4000'
    stdin_open: true
    tty: true
volumes:
  storage: